[package]
name = "hermitshell"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
portable-pty = "0.7.0"

winit = {version = "0.26"}
env_logger = "0.9"
log = "0.4"
pollster = "0.2.5"
wgpu = "0.12"
ttf-parser = "0.15.2"

nalgebra = "0.31.1"
